name: NamespaceDockerBuild

on: 
  workflow_dispatch:

jobs:
  dockerbuild:
    runs-on: [nscloud]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:latest
          file: Dockerfile
          context: .

 